### ISSUE TITLE
any fix ?

### ISSUE THREAD

**Issue by Phxnt0mWare** [Fadi002/BlankOBF-deobfuscator#1]
PS C:\Users\lmfao\Videos\BlankOBF-deobfuscator-main> python BlankOBF-Killer.py gui.py
Traceback (most recent call last):
  File "C:\Users\lmfao\Videos\BlankOBF-deobfuscator-main\BlankOBF-Killer.py", line 32, in <module>
    start_deobf()
  File "C:\Users\lmfao\Videos\BlankOBF-deobfuscator-main\BlankOBF-Killer.py", line 10, in start_deobf
    return disasm(decompressing(lzma.decompress(base64.b64decode(get_bytes(open(sys.argv[1],'r',encoding='utf-8').read())))))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lmfao\AppData\Local\Programs\Python\Python311\Lib\lzma.py", line 343, in decompress
    res = decomp.decompress(data)
          ^^^^^^^^^^^^^^^^^^^^^^^
_lzma.LZMAError: Input format not supported by decoder
PS C:\Users\lmfao\Videos\BlankOBF-deobfuscator-main>

**Comment by Fadi002** [comment]
send the code
